#### `Q-1` Create a null vector of size 10 but the fifth value which is 1.


In [2]:
import numpy as np

vector = np.empty(10)
vector[4] = 1
vector

array([            nan, 0.00000000e+000, 1.12281479e-311, 2.02369289e-320,
       1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

#### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
a = int(input("Rows in an array"))
b = int(input("Columns in an array"))

arr = np.random.random(size = (a, b))
print(arr)
avg = np.average(arr)
print(avg)

[[0.57831574 0.0267203  0.38149663 0.65960376 0.26794615]
 [0.58516006 0.337628   0.31461804 0.51974731 0.24059039]
 [0.90292856 0.17888762 0.7255954  0.01330536 0.5004125 ]
 [0.3750574  0.75214638 0.84428527 0.02255006 0.85233219]]
0.45396635484980524


#### `Q-3` Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [6]:
def createArray(a: int, b: int) -> np.array:
    arr = np.zeros((a, b))
    arr[0, :] = 1
    arr[a-1, :] = 1
    arr[:, 0] = 1
    arr[:, b-1] = 1
    return arr

createArray(4, 5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [10]:
np.linspace(0.1, 0.9, 10)

array([0.1       , 0.18888889, 0.27777778, 0.36666667, 0.45555556,
       0.54444444, 0.63333333, 0.72222222, 0.81111111, 0.9       ])

#### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [16]:
# Identy matrix of size 3-- 3X3
np.eye(3)

# Identy matrix of size 4-- 4X4
np.identity(4)

# Both are same

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [15]:
np.array([[np.random.uniform(low = 0, high = 4, size = (5))] for _ in range(5)])
# Only uniform and randint functions have the ablity to randomly create a numbers, others will create from 0 to 1

array([[[2.41000857, 0.30271153, 1.60241525, 0.44154349, 3.66925901]],

       [[0.49465459, 2.31592946, 3.70180999, 2.88144845, 3.97215061]],

       [[3.87420924, 0.31945005, 3.83869074, 3.02702917, 2.67378126]],

       [[1.89428957, 2.45766344, 3.83288832, 0.74380741, 0.40634851]],

       [[1.94647422, 3.50325199, 2.41264991, 0.55008594, 1.58570671]]])

#### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [ ]:
a = np.random.randint(low = 1, high = 100, size = (10, 2))
b = np.array([2, 3]) # b is broadcasting to the dimention same as a

np.sqrt(np.sum((a - b) ** 2, axis = 1)).astype(np.int16) # When you provide an axis to an operation between arrays that perticular axis will get eleminated

array([75, 71, 64, 77, 83, 46, 96, 66, 77, 87], dtype=int16)

#### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
np.unravel_index(100, shape = (6, 7, 8))
# The meaning is 100th element is present at index -> (1, 5, 4) in array of shape -> (6, 7, 8)

(1, 5, 4)

#### `Q-9:` Arrays

**Example 1:**
Input: `1 2 3 4 -8 -10`
Output: `[-10.  -8.   4.   3.   2.   1.]`

In [26]:
arr = input("Enter your string").strip().split(" ")
np.array(arr, dtype = np.float16)[::-1]

array([-10.,  -8.,   4.,   3.,   2.,   1.], dtype=float16)

#### `Q-10:` Elements count
Count the number of elements of a numpy array

**Example 1:**
Input: `np.array([])`
Output: `elements_count :  0`

**Example 2:**
Input: `np.array([1, 2])`
Output: `elements_count :  2`

In [27]:
a = np.zeros((2,3))
a.size

6

#### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

**Example 1:**

Input:
```Python
[86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318]
```

Output:
```Python
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```Python
[33.17344305, 45.61961654, 82.05405781, 80.9647098, 68.82830233, 91.52064278]
```

Output:
```Python
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05, 1.39571531e-10, 9.99896577e-01]
```

In [40]:
def softmax(arr: np.array) -> np.array:
    try:
        if(arr.ndim != 1):
            raise Exception("Array Dimention is not 1 - Converting to 1D array")
    except Exception as e:
        print(e)
        arr = np.ravel(arr)

    ans = np.exp(arr) / sum(np.exp(arr))  
    return ans

softmax(np.array([[[1],[2],[3]]]))

Array Dimention is not 1 - Converting to 1D array


array([0.09003057, 0.24472847, 0.66524096])

#### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

In [43]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)

a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.random.random((2,5))
vertical_stack(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.92925552, 0.16312722, 0.45212555, 0.93121306, 0.61356256],
       [0.4176856 , 0.09851088, 0.09406918, 0.97888411, 0.23794298]])

#### `Q-15:` Swap column-1 of array with column-2 in the array.

In [50]:
arr = np.random.random(size = (3,4))
arr

array([[0.98684528, 0.50579078, 0.02746836, 0.72034321],
       [0.05891077, 0.47339317, 0.29408777, 0.67619435],
       [0.67762269, 0.51372701, 0.21346949, 0.99900293]])

In [51]:
arr[:, 0], arr[:, 1] = arr[:, 1], arr[:, 0]
arr

array([[0.50579078, 0.50579078, 0.02746836, 0.72034321],
       [0.47339317, 0.47339317, 0.29408777, 0.67619435],
       [0.51372701, 0.51372701, 0.21346949, 0.99900293]])

#### `Q-16:` Replace odd elements in arrays with -1.

In [53]:
arr = np.random.randint(low = 1, high = 10, size = (3,4))
arr[arr % 2 != 0] = -1
arr

array([[-1, -1,  2, -1],
       [-1, -1, -1,  2],
       [-1, -1,  8,  4]])

#### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```python
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [54]:
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
a[a < b] = b[a < b]
a

array([6, 3, 1, 7, 8])

#### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```

In [58]:
# Given
arr = np.random.randint(low=1, high=10000, size=40).reshape(8,5)
np.round((arr[:, ::2] - np.min(arr[:, ::2])) / (np.max(arr[:, ::2]) - np.min(arr[:, ::2])), decimals = 2)

array([[0.93, 0.23, 0.65],
       [0.87, 0.49, 0.58],
       [0.52, 0.66, 0.  ],
       [0.04, 0.63, 0.35],
       [0.43, 0.31, 0.79],
       [0.92, 0.81, 1.  ],
       [0.3 , 0.2 , 0.63],
       [0.48, 0.74, 0.59]])

#### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```Python
Example1 : arr = (12,34,40,7,1,0) and n = 3, the output should be 12
Example2 : arr = (12,34,40,7,1,0) and n = 1, the output should be 40
```

In [61]:
def nthmax(arr, n):
    if n > len(arr):
        raise IndexError("n is way out of limit")
    arr = np.sort(arr)
    return arr[-n]
nthmax(np.array([12,34,40,7,1,0]),2)

34

#### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```Python
Input: a = np.array([1,2,3])
Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [77]:
a = np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [71]:
np.repeat(a, 3) # repeat each element n times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [76]:
a = np.tile(np.random.random(size = (4, 2, 5)), 2)
# The number of elements from every dimention except the outer most dimention will be become n times

(4, 2, 10)