#### `Q-1:` Generate a 3x4 matrix with random values ranging from 0 to 100. Perform the following tasks: 
- Sort the matrix using np.sort().
- Sort the matrix based on the values in the second column.
- Sort the matrix based on the maximum value in each row.
- Sort the matrix based on individual element values.

Here are some examples:
```Python
Given array:
    [[70, 60, 48],
    [ 6, 63, 93],
    [92, 90, 74],
    [15, 93, 96]]
```
```Python
i. Sorted using np.sort:
[[48, 60, 70],
 [ 6, 63, 93],
 [74, 90, 92],
 [15, 93, 96]]

ii. Sorted based on the 2nd column:
[[70, 60, 48],
 [ 6, 63, 93],
 [92, 90, 74],
 [15, 93, 96]]

iii. Sorted by the maximum value in each row (ascending):
[[70, 60, 48],
 [92, 90, 74],
 [ 6, 63, 93],
 [15, 93, 96]]

iv. Sorted by individual element values:
[[ 6, 15, 48],
 [60, 63, 70],
 [74, 90, 92],
 [93, 93, 96]]
```

In [1]:
import numpy as np
arr = np.array([[92, 90, 74], [6, 63, 93], [15, 93, 96], [70, 60, 48]])
np.sort(arr, axis = 1)

array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [3]:
arr[arr[:, 1].argsort()]

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [11]:
np.max(arr, axis = 1).argsort()[::-1]

array([2, 1, 0, 3], dtype=int64)

In [12]:
arr[np.max(arr, axis = 1).argsort()[::-1]]

array([[15, 93, 96],
       [ 6, 63, 93],
       [92, 90, 74],
       [70, 60, 48]])

In [15]:
np.sort(arr, axis = None).reshape(arr.shape)
# np.sort(arr.ravel()).reshape(arr.shape)

array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

#### `Q-2:` Given an array of marks for 5 students in 4 subjects, perform the following tasks:
- Add marks for an additional subject for each student in the same array.
- Add marks for two new students in the respective 5 subjects (including the additional subject from the previous task).
- Add an extra column with the sum of marks for all 5 subjects.
- Sort the array in non-ascending order based on the total marks column (added in the previous task) and display the top 2 rows.

Note: Adjust the dimensions of the arrays during concatenation or appending if necessary.

Given Array:
```Python
marks = [[13, 10, 9, 33],
         [63, 46, 90, 42],
         [39, 76, 13, 29],
         [82, 9, 29, 78],
         [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]

Two extra students' records:
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [25]:
arr = np.array([
    [13, 10, 9, 33],
    [63, 46, 90, 42],
    [39, 76, 13, 29],
    [82, 9, 29, 78],
    [67, 61, 59, 36]
])
extra_subject = np.array([41, 87, 72, 36, 92])
arr = np.append(arr, extra_subject.reshape(-1, 1), axis = 1)
arr

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [29]:
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])
arr = np.concatenate([arr, rec1.reshape(1, -1), rec2.reshape(1, -1)], axis = 0)
arr

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [33]:
arr = np.append(arr, np.sum(arr, axis = 1).reshape(-1, 1), axis = 1)
arr

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [41]:
arr[arr[:, -1].argsort()[:-3:-1], ::]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

#### `Q-3:` Extract unique rows and columns from a 2D array.
```Python
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Output:
```Python
Unique Rows:
[[0, 9, 1, 2, 8, 8],
 [1, 2, 3, 3, 1, 1],
 [1, 2, 3, 8, 8, 8]]

Unique Columns:
[[1, 1, 2, 3, 3],
 [0, 8, 9, 1, 2],
 [1, 8, 2, 3, 8],
 [1, 1, 2, 3, 3]]
```

In [42]:
arr = np.array([
    [1,2,3,3,1,1],
    [0,9,1,2,8,8],
    [1,2,3,8,8,8],
    [1,2,3,3,1,1]
])
np.unique(arr, axis = 1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

In [43]:
arr = np.array([
    [1,2,3,3,1,1],
    [0,9,1,2,8,8],
    [1,2,3,8,8,8],
    [1,2,3,3,1,1]
])
np.unique(arr, axis = 0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

#### `Q-4:` Flip given 2-D array along both axes at the same time.

In [1]:
import numpy as np
arr = np.array([
    [1,2,3,3,1,1],
    [0,9,1,2,8,8],
    [1,2,3,8,8,8],
    [1,2,3,3,1,1]
])
np.flip(np.flip(arr, axis = 0), axis = 1)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

#### `Q-5:` Get row numbers of NumPy array having element larger than X.
```Python
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [6]:
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
np.unique(np.where(arr > 6)[0])

array([1, 3], dtype=int64)

#### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [7]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [9]:
arr2.flatten()

array([3, 4, 5, 6])

In [10]:
arr3.ravel()

array([7, 8, 9])

In [11]:
arr3.reshape(-1)

array([7, 8, 9])

#### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [13]:
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr = arr[(np.max(arr) != arr) & (np.min(arr) != arr)]
arr

array([756, 198, 457, 769, 156, 989, 681, 112, 568, 717, 468, 278, 654,
       638, 113, 496, 200, 450, 465, 623, 648, 519, 621, 335, 254, 932,
       547, 869, 196, 305, 733, 279, 739, 284, 607, 560, 585, 944, 777,
       181, 850, 724, 954, 475, 398, 271, 451, 791, 672, 504, 518, 640,
       513, 264, 478, 431, 377, 174, 916, 937, 807, 106, 188, 318, 124,
       803, 901, 368, 821, 123, 278, 254, 762, 170, 658, 233, 207, 707,
       784, 708, 688, 129, 168, 543, 940, 747, 816, 727, 691, 731, 527,
       220, 823, 658, 836, 936, 266, 564, 702, 922, 696, 108, 754, 870,
       287, 541, 152, 498, 650, 267, 680, 197, 320, 529, 688, 844, 347,
       736, 187, 588, 444, 855, 533, 362, 784, 326, 496, 760, 349, 419,
       728, 838, 579, 631, 804, 572, 983, 809, 784, 608, 567, 664, 373,
       728, 599, 428, 242, 681, 829, 356, 559, 643, 542, 965, 949, 361,
       415, 566, 292, 363, 686, 478, 511, 235, 213, 971, 145, 530, 409,
       479, 114, 545, 643, 683, 483, 618, 619, 951, 777, 762, 15

#### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [17]:
arr = np.array([1000, 900, 700, 200, 100, 90])
np.cumsum(np.sort(np.clip(arr, a_max=700, a_min=100)), axis = 0)

array([ 100,  200,  400, 1100, 1800, 2500])

#### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [18]:
arr = np.random.random(size = (100))
arr = np.round(arr, decimals = 3)

# 1st
np.percentile(arr, 0) == np.min(arr)

True

In [19]:
# 2nd
np.percentile(arr, 100) == np.max(arr)

True

In [20]:
# 3rd
np.percentile(arr, 51) - np.percentile(arr, 50)

0.0024899999999999922